//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscapeRoom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public string Title { get; set; }
        public string Tag { get; set; }
        public string Description { get; set; }
        public int Capacity { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<System.DateTime> RunStart { get; set; }
        public Nullable<System.DateTime> RunEnd { get; set; }
        public string Banner { get; set; }
        public string Button { get; set; }
        public string Color { get; set; }
        public string LongPic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
